- name: creating the bastion host
  hosts: localhost
  become: true
  connection: local
  gather_facts: false
  tasks:
    - name: importing the variables files
      include_vars: vars/bastion_setup

    - name: importing the variables files1
      include_vars: vars/vpc-output.var

    - name: importing the variables files2
      include_vars: vars/vpc_setup

    - name: creating the ec2 key pair
      ec2_key:
        name: vprofile-key
        region: "{{region}}"
        state: present
      register: keyout

    - debug:
        var: keyout

    - name: saving the ec2_key pair
      copy:
        content: "{{keyout.key.private_key}}"
        dest: "./vprofile-key.pem"
        mode: 0600
      when: keyout.changed

    - name: creating the security group for bastion host
      ec2_group:
        name: bastionsg
        description: allow port 22 for bastion host
        vpc_id: "{{vpcoutid}}"
        region: "{{region}}"
        state: present
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: "{{MYIP}}"
        tags:
          Name: bastion-sg
      register: bastionsg_out

    - name: creating the bastion host
      ec2:
        key_name: vprofile-key
        region: "{{region}}"
        wait: yes
        wait_timeout: 200
        instance_type: t2.micro
        image: "{{bastion_ami}}"
        instance_tags:
          Name: bastion-host
          project: vprofile
          owner: Devopsteam
        exact_count: 1
        count_tag:
          Name: bastion-host
          project: vprofile
          owner: Devopsteam
        group_id: "{{bastionsg_out.group_id}}"
        vpc_subnet_id: "{{pubsub1id}}"
      register: bastionhost_out

    - name: insert and update the vpc-output file
      blockinfile:
        path: vars/vpc-output.var
        backup: yes
        block: |
          bastionsgid: {{bastionhost_out.group_id}}
